ci: Remove Qodana workflow temporarily
Qodana workflow is failing due to unavailable Docker image
(jetbrains/qodana-jvm-community:2026.1). Removing until stable
version is available or alternative code quality tool is configured.

Error: couldn't create the container - No such image